/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadulp.views;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadulp.Entidades.*;
import universidadulp.accesoADatos.AlumnoData;
import universidadulp.accesoADatos.InscripcionData;

/**
 *
 * @author calo_
 */
public class ActualizacionesNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ActualizacionesNotas
     */
     private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return c == 2;
        }
    };
    private void armarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nota");
        jtTableIns.setModel(modelo);
    }
    
    private void rellenarLista(){
        AlumnoData aluData= new AlumnoData();
        ArrayList<Alumno> listaAlumnos=aluData.listarAlumnos();
        jtComboBoxAct.removeAllItems();
        for (Alumno alumno : listaAlumnos) {
            jtComboBoxAct.addItem(new Alumno(alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(),
                    alumno.getNombre(), alumno.getFechaNacimiento(), alumno.isActivo()));
        }
    }
    
    private void mostrarNotas(){
        InscripcionData ins = new InscripcionData();
        int id = jtComboBoxAct.getItemAt(jtComboBoxAct.getSelectedIndex()).getIdAlumno();
       
        List<Inscripcion> listaInscripcion=ins.obtenerInscripcionesPorAlumno(id);
        for (Inscripcion inscripcion : listaInscripcion) {
          
            modelo.addRow(new Object[]{
                inscripcion.getMateria().getIdMateria(),
                inscripcion.getMateria().getNombre(),
                inscripcion.getNota()
            });
        }
        
    }
    
    private void actualizarNota(){
        
        
        try{
            int filaSeleccionada = jtTableIns.getSelectedRow();
        Object[] datosFila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < modelo.getColumnCount(); i++) {
                datosFila[i] = modelo.getValueAt(filaSeleccionada, i);
            }
       
        // int idMateria=Integer.parseInt(modelo.getValueAt(filaSeleccionada,0).toString);
        // double nota=Double.parseDouble(modelo.getValueAt(filaSeleccionada,2).toString);
        
        String aux = datosFila[0].toString();
        String aux2 = datosFila[2].toString();
        
        double nota = Integer.parseInt(aux2);
        int idAlumno = jtComboBoxAct.getItemAt(jtComboBoxAct.getSelectedIndex()).getIdAlumno();
        int idMateria = Integer.parseInt(aux);
       
        
        if(nota > 10 || nota < 0){
            JOptionPane.showMessageDialog(null, "Ingrese una nota valida");
        } else {
            InscripcionData insc = new InscripcionData();
        insc.actualizarNota(idAlumno, idMateria, nota);
        }
        } catch(java.lang.ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Presione enter para ingresar la nota");
        }
        
            
        
    }
        
        
    
    private void borrarFilas(){
        
        int f = jtTableIns.getRowCount()-1;
        for(;f>=0;f--){
            modelo.removeRow(f);
        }
    }
    
    public ActualizacionesNotas() {
        initComponents();
        armarCabecera();
        rellenarLista();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtComboBoxAct = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTableIns = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(706, 554));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carga de notas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona un alumno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        jtComboBoxAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtComboBoxActActionPerformed(evt);
            }
        });
        jtComboBoxAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtComboBoxActKeyReleased(evt);
            }
        });
        jPanel1.add(jtComboBoxAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 280, 20));

        jtTableIns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTableIns);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 441, 178));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 40, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Guardar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 430, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtComboBoxActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtComboBoxActActionPerformed
        // TODO add your handling code here:
         borrarFilas();
         mostrarNotas();
         
    }//GEN-LAST:event_jtComboBoxActActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        actualizarNota();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtComboBoxActKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtComboBoxActKeyReleased
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jtComboBoxActKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<Alumno> jtComboBoxAct;
    private javax.swing.JTable jtTableIns;
    // End of variables declaration//GEN-END:variables
}
