/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadulp.Views;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import universidadulp.Entidades.*;
import universidadulp.accesoADatos.AlumnoData;
import universidadulp.accesoADatos.InscripcionData;

/**
 *
 * @author Sergio
 */
public class InscripcionesView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    private void armarCabecera() {
        modelo.addColumn("ID Materia");
        modelo.addColumn("Nombre");

        modelo.addColumn("Año");
        jtablaMaterias.setModel(modelo);
    }

    private void llenarAlumnos() {
        AlumnoData aluData = new AlumnoData();
        ArrayList<Alumno> listaAlumnos = aluData.listarAlumnos();
        jComboListaAlumno.removeAllItems();
        for (Alumno alumno : listaAlumnos) {
            jComboListaAlumno.addItem(new Alumno(alumno.getIdAlumno(), alumno.getDni(), alumno.getApellido(),
                    alumno.getNombre(), alumno.getFechaNacimiento(), alumno.isActivo()));
        }
    }

    public InscripcionesView() {
        initComponents();
        armarCabecera();
        llenarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboListaAlumno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrInscriptas = new javax.swing.JRadioButton();
        jrNOInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularInscrip = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 38, 113));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de Inscripción");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione un alumno:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jComboListaAlumno.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jComboListaAlumnoComponentShown(evt);
            }
        });
        jComboListaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboListaAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboListaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Listado de Materias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        buttonGroup1.add(jrInscriptas);
        jrInscriptas.setText("Materias inscriptas");
        jrInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(jrInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        buttonGroup1.add(jrNOInscriptas);
        jrNOInscriptas.setText("Materias no Inscriptas");
        jrNOInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNOInscriptasActionPerformed(evt);
            }
        });
        jPanel1.add(jrNOInscriptas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jtablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablaMaterias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 640, 240));

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });
        jPanel1.add(jbInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        jbAnularInscrip.setText("Anular Inscripción");
        jbAnularInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripActionPerformed(evt);
            }
        });
        jPanel1.add(jbAnularInscrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.jpg"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 40, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 540, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboListaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboListaAlumnoActionPerformed
        // TODO add your handling code here:
        if (jrInscriptas.isSelected()) {
            jbInscribir.setEnabled(false);
            jbAnularInscrip.setEnabled(true);
            modelo.setRowCount(0);
            InscripcionData inscripData = new InscripcionData();
            int id = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex()).getIdAlumno();
            for (Materia materiasCursadas : inscripData.obtenerMateriasCursadas(id)) {
                modelo.addRow(new Object[]{
                    materiasCursadas.getIdMateria(),
                    materiasCursadas.getNombre(),
                    materiasCursadas.getAnioMateria()
                });
            }
        } else if (jrNOInscriptas.isSelected()) {
            jbInscribir.setEnabled(true);
            jbAnularInscrip.setEnabled(false);
            modelo.setRowCount(0);
            InscripcionData inscripData = new InscripcionData();
            int id = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex()).getIdAlumno();
            for (Materia materiasNOCursada : inscripData.obtenerMateriasNOCursadas(id)) {
                modelo.addRow(new Object[]{
                    materiasNOCursada.getIdMateria(),
                    materiasNOCursada.getNombre(),
                    materiasNOCursada.getAnioMateria()
                });
            }
        }
    }//GEN-LAST:event_jComboListaAlumnoActionPerformed

    private void jrInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrInscriptasActionPerformed
        // TODO add your handling code here:
        jbInscribir.setEnabled(false);
        jbAnularInscrip.setEnabled(true);
        modelo.setRowCount(0);
        InscripcionData inscripData = new InscripcionData();
        int id = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex()).getIdAlumno();
        for (Materia materiasCursadas : inscripData.obtenerMateriasCursadas(id)) {
            modelo.addRow(new Object[]{
                materiasCursadas.getIdMateria(),
                materiasCursadas.getNombre(),
                materiasCursadas.getAnioMateria()
            });

        }


    }//GEN-LAST:event_jrInscriptasActionPerformed

    private void jComboListaAlumnoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboListaAlumnoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboListaAlumnoComponentShown

    private void jrNOInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNOInscriptasActionPerformed
        // TODO add your handling code here:
        jbInscribir.setEnabled(true);
        jbAnularInscrip.setEnabled(false);
        modelo.setRowCount(0);
        InscripcionData inscripData = new InscripcionData();
        int id = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex()).getIdAlumno();
        for (Materia materiasNOCursada : inscripData.obtenerMateriasNOCursadas(id)) {
            modelo.addRow(new Object[]{
                materiasNOCursada.getIdMateria(),
                materiasNOCursada.getNombre(),
                materiasNOCursada.getAnioMateria()
            });

        }

    }//GEN-LAST:event_jrNOInscriptasActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAnularInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripActionPerformed
        // TODO add your handling code here:
        InscripcionData inscripData = new InscripcionData();

        int filaS = jtablaMaterias.getSelectedRow();
        int idMateria = Integer.parseInt(jtablaMaterias.getValueAt(filaS, 0).toString());
        int idAlumno = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex()).getIdAlumno();
        if (filaS != -1) {
            inscripData.borrarInscripcionMateriaAlumno(idAlumno, idMateria);

            modelo.removeRow(filaS);

        } else {
            JOptionPane.showMessageDialog(this, "Usted debe seleccionar una fila.");
        }

    }//GEN-LAST:event_jbAnularInscripActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        InscripcionData inscripData = new InscripcionData();

        int filaS = jtablaMaterias.getSelectedRow();
        int idMateria, añoMateria;
        String nombreMateria;
        if (filaS != -1) {
            Alumno alumno = jComboListaAlumno.getItemAt(jComboListaAlumno.getSelectedIndex());

            idMateria = Integer.parseInt(jtablaMaterias.getValueAt(filaS, 0).toString());
            nombreMateria = jtablaMaterias.getValueAt(filaS, 1).toString();
            añoMateria = Integer.parseInt(jtablaMaterias.getValueAt(filaS, 2).toString());
            Materia materia = new Materia(idMateria, nombreMateria, añoMateria, true);
            Inscripcion inscrip = new Inscripcion(alumno, materia, 0.0);

            inscripData.guardarInscripcion(inscrip);
            modelo.removeRow(filaS);

        } else {
            JOptionPane.showMessageDialog(this, "Usted debe seleccionar una fila.");
        }
    }//GEN-LAST:event_jbInscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Alumno> jComboListaAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAnularInscrip;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrInscriptas;
    private javax.swing.JRadioButton jrNOInscriptas;
    private javax.swing.JTable jtablaMaterias;
    // End of variables declaration//GEN-END:variables
}
